Enhanced rigid contact API
pyomeca/biorbd pull request #249
Opened 2021-12-17 22:20 UTC by Ipuch

Enhanced features for rigid contacts iPython API such as :
- position in global frame
- velocity in global frame
- acceleration in global frame

2021-12-17 22:29 UTC, Ipuch commented
I succeeded in compiling in my debug and eigen but not in casadi release.

2021-12-21 15:36 UTC, pariterre requested changes
GG, just a very quick test and we are good to go

2021-12-21 15:36 UTC, pariterre commented on src/RigidBody/Contacts.cpp
> +    m_rigidContacts->push_back(NodeSegment(body_point, name, "",true,false, axis.c_str(),body_id));
This is the best I could do... but I am not sure this is okay, could you add a test to validate that when you call this function it actually adds the axis properly?

2021-12-22 16:47 UTC, pariterre approved these changes
LGTM

2021-12-22 16:47 UTC, pariterre commented on src/RigidBody/Contacts.cpp
> +    m_rigidContacts->push_back(NodeSegment(body_point, name, "",true,false, axis.c_str(),body_id));
this works

2021-12-22 16:47 UTC, merged