Passive torque
pyomeca/biorbd pull request #312
Opened 2022-11-11 18:32 UTC by aceglia

To address the PR #218. 
For now passive torque implemented are linear and constant.

2022-11-11 19:58 UTC, aceglia commented
@pariterre Everything is fine locally on two of my computers so I don't know why github action crash...

2022-11-17 19:23 UTC, pariterre requested changes
> Reviewed 20 of 30 files at r1, 41 of 41 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/312)* status: all files reviewed, 23 unresolved discussions (waiting on @aceglia)

___
*[`binding/biorbd_passive_torques.i.in` line 1 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5silvCVvqE0nPMftI:-NH5silvCVvqE0nPMftJ:bols8me) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/binding/biorbd_passive_torques.i.in#L1)):*
> ```
> // File : biorbd_muscles.i
> ```

Update comments
___
*[`include/InternalForces/Muscles/Muscle.h` line 6 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5uclgETWjxRmpFomn:-NH5uclgETWjxRmpFomo:b2zd5t7) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/include/InternalForces/Muscles/Muscle.h#L6)):*
> ```objc
> #include "biorbdConfig.h"
> #include "InternalForces/Compound.h"
> #include "InternalForces/Geometry.h"
> ```

Try minimizing as much as possible actual imports in a .h file. use forward declaration instead



_Code quote:_
```objc
#include "InternalForces/Geometry.h"
```
___
*[`include/InternalForces/Muscles/Muscles.h` line 8 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5vB5i1CfjnAEXe_eF:-NH5vB5i1CfjnAEXe_eG:bjnlt4x) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/include/InternalForces/Muscles/Muscles.h#L8)):*
> ```objc
> 
> #include "biorbdConfig.h"
> #include "InternalForces/Geometry.h"
> ```

Use forward declaration
___
*[`include/InternalForces/PassiveTorques/PassiveTorqueExponential.h` line 120 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5w0M-A_b_mjpmmbuL:-NH5w0M-A_b_mjpmmbuM:b-xfz3vs) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/include/InternalForces/PassiveTorques/PassiveTorqueExponential.h#L120)):*
> ```objc
>     virtual void setType();
> 
>     // (B1 * np.exp(k1 * (q-qmid)) + B2 * np.exp(k2 * (q-qmid))) * (1-p_beta*qdot/(s_v*omega_max)) * (q[0] - delta_p) + tau_eq
> ```

Move this to the class description



_Code quote:_
```objc
// (B1 * np.exp(k1 * (q-qmid)) + B2 * np.exp(k2 * (q-qmid))) * (1-p_beta*qdot/(s_v*omega_max)) * (q[0] - delta_p) + tau_eq
```
___
*[`include/InternalForces/PassiveTorques/PassiveTorqueLinear.h` line 103 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5wEAd5jkMKYcEC4ih:-NH5wEAd5jkMKYcEC4ii:b-8sgfra) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/include/InternalForces/PassiveTorques/PassiveTorqueLinear.h#L103)):*
> ```objc
>     virtual void setType();
> 
>     // mx+b
> ```

Move this to the start of the class
___
*[`src/ModelReader.cpp` line 1110 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5xdD10To105ECOWl9:-NH5xdD10To105ECOWlA:b-plpt1o) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/ModelReader.cpp#L1110)):*
> ```cpp
>                 }
>                 // Verify that everything is there
>                 utils::Error::check(isTypeSet!=0, "PassiveTorque type must be defined");
> ```

isnan instead of isSet everywhere?



_Code quote:_
```cpp
isTypeSet!=0
```
___
*[`src/ModelReader.cpp` line 1116 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5xoNL5ZDeOT5TXgEp:-NH5xoNL5ZDeOT5TXgEq:b-ripxz1) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/ModelReader.cpp#L1116)):*
> ```cpp
>                                                 "Make sure all parameters are defined");
>                     passiveTorque = new internal_forces::passive_torques::PassiveTorqueConstant(Tconstant,dofIdx,
>                             name);
> ```

Is there a reson for the line return on this single variable?



_Code quote:_
```cpp
                    passiveTorque = new internal_forces::passive_torques::PassiveTorqueConstant(Tconstant,dofIdx,
                            name);
```
___
*[`src/ModelReader.cpp` line 1123 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5yHtA7RDLIdj2TLB9:-NH5yHtA7RDLIdj2TLBA:bci608h) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/ModelReader.cpp#L1123)):*
> ```cpp
>                             name);
>                 } else if (!type.tolower().compare("exponential")) {
>                     utils::Error::check(isDofSet && isExponentialSet && isWMaxSet,
> ```

regroup WMax?



_Code quote:_
```cpp
isExponentialSet && isWMaxSet
```
___
*[`src/ModelReader.cpp` line 1133 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5wkXxEii_gEMfPtqj:-NH5wkXxEii_gEMfPtqk:bv9o4y1) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/ModelReader.cpp#L1133)):*
> ```cpp
> //                    passiveTorque = new internal_forces::passive_torques::PassiveTorqueConstant(Tmax, dofIdx,
> //                            name); // Échec de compilation sinon
> //#endif
> ```

To be removed if not need



_Code quote:_
```cpp
//#ifdef _WIN32
//                    passiveTorque = new internal_forces::passive_torques::PassiveTorqueConstant(Tmax, dofIdx,
//                            name); // Échec de compilation sinon
//#endif
```
___
*[`src/InternalForces/PassiveTorques/PassiveTorqueLinear.cpp` line 3 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5zsfh4vOTnW5iMMiW:-NH5zsfh4vOTnW5iMMiX:b-9e8oi9) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/InternalForces/PassiveTorques/PassiveTorqueLinear.cpp#L3)):*
> ```cpp
> #define BIORBD_API_EXPORTS
> #include "InternalForces/PassiveTorques/PassiveTorqueLinear.h"
> ```

remove space
___
*[`src/InternalForces/PassiveTorques/PassiveTorqueLinear.cpp` line 14 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH6---vBDuVsbt4aUBb:-NH6---vBDuVsbt4aUBc:b-vykayf) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/InternalForces/PassiveTorques/PassiveTorqueLinear.cpp#L14)):*
> ```cpp
>     m_b(std::make_shared<utils::Scalar>(0))
> {
>     setType();
> ```

This should appear in all the constructor of "PassiveTorque", but this is useless elsewhere



_Code quote:_
```cpp
setType()
```
___
*[`src/InternalForces/PassiveTorques/PassiveTorqueLinear.cpp` line 79 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH6-Qs_E8ZUNRl3Bsft:-NH6-Qs_E8ZUNRl3Bsfu:b-93o1j8) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/InternalForces/PassiveTorques/PassiveTorqueLinear.cpp#L79)):*
> ```cpp
>     const rigidbody::GeneralizedCoordinates &Q) const
> {
>     return (Q[*m_dofIdx]*180/M_PI) * *m_m + *m_b;
> ```

Put it in radian for now



_Code quote:_
```cpp
(Q[*m_dofIdx]*180/M_PI)
```
___
*[`src/InternalForces/PassiveTorques/PassiveTorques.cpp` line 19 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH60XQA0rg5HhQPDc0M:-NH60XQA0rg5HhQPDc0N:bb7pcsz) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/InternalForces/PassiveTorques/PassiveTorques.cpp#L19)):*
> ```cpp
> internal_forces::passive_torques::PassiveTorques::PassiveTorques() :
>     m_pas(std::make_shared<std::vector<std::shared_ptr<internal_forces::passive_torques::PassiveTorque>>>()),
>     m_isDofSet(std::make_shared<std::vector<bool>>(1)),
> ```

true



_Code quote:_
```cpp
1
```
___
*[`src/InternalForces/PassiveTorques/PassiveTorques.cpp` line 58 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH611sOAA-ewpih5DP-:-NH611sOAA-ewpih5DP0:b-avw38k) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/InternalForces/PassiveTorques/PassiveTorques.cpp#L58)):*
> ```cpp
>         }
>     }
>     *m_isClose = *other.m_isClose;
> ```

This is probably useless



_Code quote:_
```cpp
*m_isClose = *other.m_isClose;
```
___
*[`src/InternalF [...]

2022-11-17 21:14 UTC, aceglia reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/312)* status: 59 of 61 files reviewed, 23 unresolved discussions (waiting on @pariterre)

___
*[`binding/biorbd_passive_torques.i.in` line 1 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5silvCVvqE0nPMftI:-NH68LSi2dKOldnNF08x:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/binding/biorbd_passive_torques.i.in#L1)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Update comments
</blockquote></details>

Done.
___
*[`include/InternalForces/Muscles/Muscle.h` line 6 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5uclgETWjxRmpFomn:-NH6H4LwEkRDefiTijIJ:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/include/InternalForces/Muscles/Muscle.h#L6)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Try minimizing as much as possible actual imports in a .h file. use forward declaration instead
</blockquote></details>

Done.
___
*[`include/InternalForces/Muscles/Muscles.h` line 8 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5vB5i1CfjnAEXe_eF:-NH6H7ya4Ib7zstseGOd:bjn2321) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/include/InternalForces/Muscles/Muscles.h#L8)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Use forward declaration
</blockquote></details>

Have to keep it for this one. 
___
*[`include/InternalForces/PassiveTorques/PassiveTorqueExponential.h` line 120 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5w0M-A_b_mjpmmbuL:-NH6I-mX-b-2gLRd6Dq7:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/include/InternalForces/PassiveTorques/PassiveTorqueExponential.h#L120)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Move this to the class description
</blockquote></details>

Done.
___
*[`include/InternalForces/PassiveTorques/PassiveTorqueLinear.h` line 103 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5wEAd5jkMKYcEC4ih:-NH6ICmn6cCrRzhmlmpX:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/include/InternalForces/PassiveTorques/PassiveTorqueLinear.h#L103)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Move this to the start of the class
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1110 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5xdD10To105ECOWl9:-NH6JlIw43IRpLdIh4tu:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/ModelReader.cpp#L1110)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

isnan instead of isSet everywhere?
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1116 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5xoNL5ZDeOT5TXgEp:-NH6K09-932m6HwNuFYy:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/ModelReader.cpp#L1116)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Is there a reson for the line return on this single variable?
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1123 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5yHtA7RDLIdj2TLB9:-NH6K2999CUbO5mkifMs:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/ModelReader.cpp#L1123)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

regroup WMax?
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1133 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5wkXxEii_gEMfPtqj:-NH6K4fWDcdN4hdPFdkL:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/ModelReader.cpp#L1133)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To be removed if not need
</blockquote></details>

Done.
___
*[`src/InternalForces/PassiveTorques/PassiveTorqueLinear.cpp` line 3 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5zsfh4vOTnW5iMMiW:-NH6L3mA9MVnTq7LrBOE:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/InternalForces/PassiveTorques/PassiveTorqueLinear.cpp#L3)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

remove space
</blockquote></details>

Done.
___
*[`src/InternalForces/PassiveTorques/PassiveTorqueLinear.cpp` line 14 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH6---vBDuVsbt4aUBb:-NH6LjBF4VJ1Zekgm0MT:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/InternalForces/PassiveTorques/PassiveTorqueLinear.cpp#L14)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should appear in all the constructor of "PassiveTorque", but this is useless elsewhere
</blockquote></details>

Done.
___
*[`src/InternalForces/PassiveTorques/PassiveTorqueLinear.cpp` line 79 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH6-Qs_E8ZUNRl3Bsft:-NH6MA7wAVu5VPCkxWjN:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/InternalForces/PassiveTorques/PassiveTorqueLinear.cpp#L79)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Put it in radian for now
</blockquote></details>

Done.
___
*[`src/InternalForces/PassiveTorques/PassiveTorques.cpp` line 19 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH60XQA0rg5HhQPDc0M:-NH6Noje-T-X4e40LhtY:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/InternalForces/PassiveTorques/PassiveTorques.cpp#L19)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

true
</blockquote></details>

Done.
___
*[`src/InternalForces/PassiveTorques/PassiveTorques.cpp` line 58 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH611sOAA-ewpih5DP-:-NH6NqGG09I37uJmoUIK:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/InternalForces/PassiveTorques/PassiveTorques.cpp#L58)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This is probably useless
</blockquote></details>

Done.
___
*[`src/InternalForces/PassiveTorques/PassiveTorques.cpp` line 63 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH61Eaz7jkvi-eZObpR:-NH6OPKl9SeJbe_of4O4:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/InternalForces/PassiveTorques/PassiveTorques.cpp#L63)):*
> ```cpp
> 
> 
> void internal_forces::passive_torques::PassiveTorques::addPassiveTorque(const internal_forces::passive_torques::PassiveTorque
> ```

Done.
___
*[`src/InternalForces/PassiveTorques/PassiveTorques.cpp` line 64 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH615BA6_D9GMITfgum:-NH6OQP08lINtl_EgvBE:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/InternalForces/PassiveTorques/PassiveTorques.cpp#L64)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

use long names
</blockquote></details>

Done.
___
*[`src/InternalForces/PassiveTorques/PassiveTorques.cpp` line 67 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH61JxH1Lk12jVd6Zz1:-NH6OS5D019Ytcl1A8z0:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/InternalForces/PassiveTorques/PassiveTorques.cpp#L67)):*
<details [...]

2022-11-17 23:05 UTC, aceglia reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/312)* status: 41 of 63 files reviewed, 23 unresolved discussions (waiting on @pariterre)

___
*[`src/InternalForces/PassiveTorques/PassiveTorqueLinear.cpp` line 14 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH6---vBDuVsbt4aUBb:-NH6pZYeE92lQ3rv-knE:b-kfbsnd) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/src/InternalForces/PassiveTorques/PassiveTorqueLinear.cpp#L14)):*
<details><summary><i>Previously, aceglia wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Infact I need it cause in the Passive torque class the function setType return No-type. It is the same in muscle class. 


<!-- Sent from Reviewable.io -->

2022-11-18 17:34 UTC, aceglia commented
@pariterre RTR

2022-11-24 18:54 UTC, pariterre requested changes
> Reviewed 2 of 2 files at r3, 49 of 49 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/312)* status: all files reviewed, 9 unresolved discussions (waiting on @aceglia)

___
*[`examples/cpp_eigen_installed/test.cflags` line 1 at r4](https://reviewable.io/reviews/pyomeca/biorbd/312#-NHewUhP1qnn62xyUhd6:-NHewUhP1qnn62xyUhd7:b-q3t7h5) ([raw file](https://github.com/pyomeca/biorbd/blob/a4178563495f4313bd311ccbf6154af95cda231a/examples/cpp_eigen_installed/test.cflags#L1)):*
> ```
> -std=c17
> ```

I don't think this file is supposed to be added...



_Code quote:_
```
-std=c17
```
___
*[`examples/cpp_eigen_installed/test.config` line 1 at r4](https://reviewable.io/reviews/pyomeca/biorbd/312#-NHewZzoBWeo_nqYmI0q:-NHewZzoBWeo_nqYmI0r:b8iwxev) ([raw file](https://github.com/pyomeca/biorbd/blob/a4178563495f4313bd311ccbf6154af95cda231a/examples/cpp_eigen_installed/test.config#L1)):*
> ```
> // Add predefined macros for your project here. For example:
> ```

I don't think this file is supposed to be added



_Code quote:_
```
// Add predefined macros for your project here. For example:
// #define THE_ANSWER 42
```
___
*[`examples/cpp_eigen_installed/test.creator` line 1 at r4](https://reviewable.io/reviews/pyomeca/biorbd/312#-NHewcES9-5JGEvclPK2:-NHewcES9-5JGEvclPK3:b8iwxev) ([raw file](https://github.com/pyomeca/biorbd/blob/a4178563495f4313bd311ccbf6154af95cda231a/examples/cpp_eigen_installed/test.creator#L1)):*
> ```
> [General]
> ```

I don't think this file is supposed to be added
___
*[`examples/cpp_eigen_installed/test.cxxflags` line 1 at r4](https://reviewable.io/reviews/pyomeca/biorbd/312#-NHewcu0EOmi9TJUqPz9:-NHewcu0EOmi9TJUqPzA:b8iwxev) ([raw file](https://github.com/pyomeca/biorbd/blob/a4178563495f4313bd311ccbf6154af95cda231a/examples/cpp_eigen_installed/test.cxxflags#L1)):*
> ```
> -std=c++17
> ```

I don't think this file is supposed to be added
___
*[`examples/cpp_eigen_installed/test.files` line 1 at r4](https://reviewable.io/reviews/pyomeca/biorbd/312#-NHewdyLCkVGgtzzz2Dh:-NHewdyLCkVGgtzzz2Di:b8iwxev) ([raw file](https://github.com/pyomeca/biorbd/blob/a4178563495f4313bd311ccbf6154af95cda231a/examples/cpp_eigen_installed/test.files#L1)):*
> ```
> CMakeLists.txt
> ```

I don't think this file is supposed to be added
___
*[`examples/cpp_eigen_installed/test.includes` line 0 at r4](https://reviewable.io/reviews/pyomeca/biorbd/312#-NHewezD6RS-FBcdfomJ:-NHewezD6RS-FBcdfomK:b8iwxev) ([raw file](https://github.com/pyomeca/biorbd/blob/a4178563495f4313bd311ccbf6154af95cda231a/examples/cpp_eigen_installed/test.includes#L0)):*
I don't think this file is supposed to be added
___
*[`include/InternalForces/Muscles/Muscle.h` line 6 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5uclgETWjxRmpFomn:-NHexHpR4a_5M555y4If:b3u26bo) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/include/InternalForces/Muscles/Muscle.h#L6)):*
<details><summary><i>Previously, aceglia wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You did not remove the include but moved it. If should be forward declaration
___
*[`src/ModelReader.cpp` line 1107 at r4](https://reviewable.io/reviews/pyomeca/biorbd/312#-NHey8zE9MERV906lDEg:-NHey8zE9MERV906lDEh:but69s2) ([raw file](https://github.com/pyomeca/biorbd/blob/a4178563495f4313bd311ccbf6154af95cda231a/src/ModelReader.cpp#L1107)):*
> ```cpp
>                     passiveTorque = new internal_forces::passive_torques::PassiveTorqueConstant(Tconstant,dofIdx,name);
>                 } else if (!type.tolower().compare("linear")) {
>                     utils::Error::check(isDofSet && std::isnan(slope) == 0 && std::isnan(T0) == 0,
> ```

Did you mean `!std::isnan(slope)`?



_Code quote:_
```cpp
std::isnan(slope) == 0
```
___
*[`src/InternalForces/PassiveTorques/PassiveTorques.cpp` line 61 at r4](https://reviewable.io/reviews/pyomeca/biorbd/312#-NHezJ812zqYsgv6VSt8:-NHezJ812zqYsgv6VSt9:bql4a2m) ([raw file](https://github.com/pyomeca/biorbd/blob/a4178563495f4313bd311ccbf6154af95cda231a/src/InternalForces/PassiveTorques/PassiveTorques.cpp#L61)):*
> ```cpp
> 
> void internal_forces::passive_torques::PassiveTorques::addPassiveTorque(
>         const internal_forces::passive_torques::PassiveTorque &torqueTp)
> ```

Typically, you would use `other`. What means `Tp`?



_Code quote:_
```cpp
torqueTp
```


<!-- Sent from Reviewable.io -->

2022-11-24 19:25 UTC, aceglia reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/312)* status: all files reviewed, 9 unresolved discussions (waiting on @pariterre)

___
*[`examples/cpp_eigen_installed/test.cflags` line 1 at r4](https://reviewable.io/reviews/pyomeca/biorbd/312#-NHewUhP1qnn62xyUhd6:-NHf1rJI2w2v6qQGysqH:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/a4178563495f4313bd311ccbf6154af95cda231a/examples/cpp_eigen_installed/test.cflags#L1)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I don't think this file is supposed to be added...
</blockquote></details>

Done.
___
*[`examples/cpp_eigen_installed/test.config` line 1 at r4](https://reviewable.io/reviews/pyomeca/biorbd/312#-NHewZzoBWeo_nqYmI0q:-NHf1tNTE-ezkm8dLdzQ:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/a4178563495f4313bd311ccbf6154af95cda231a/examples/cpp_eigen_installed/test.config#L1)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I don't think this file is supposed to be added
</blockquote></details>

Done.
___
*[`examples/cpp_eigen_installed/test.creator` line 1 at r4](https://reviewable.io/reviews/pyomeca/biorbd/312#-NHewcES9-5JGEvclPK2:-NHf1u1eD-IR9E1u51rd:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/a4178563495f4313bd311ccbf6154af95cda231a/examples/cpp_eigen_installed/test.creator#L1)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I don't think this file is supposed to be added
</blockquote></details>

Done.
___
*[`examples/cpp_eigen_installed/test.cxxflags` line 1 at r4](https://reviewable.io/reviews/pyomeca/biorbd/312#-NHewcu0EOmi9TJUqPz9:-NHf1uTFBYG3jzjWTo4w:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/a4178563495f4313bd311ccbf6154af95cda231a/examples/cpp_eigen_installed/test.cxxflags#L1)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I don't think this file is supposed to be added
</blockquote></details>

Done.
___
*[`examples/cpp_eigen_installed/test.files` line 1 at r4](https://reviewable.io/reviews/pyomeca/biorbd/312#-NHewdyLCkVGgtzzz2Dh:-NHf1unNDTKwzBoe_bHh:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/a4178563495f4313bd311ccbf6154af95cda231a/examples/cpp_eigen_installed/test.files#L1)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I don't think this file is supposed to be added
</blockquote></details>

Done.
___
*[`examples/cpp_eigen_installed/test.includes` line  at r4](https://reviewable.io/reviews/pyomeca/biorbd/312#-NHewezD6RS-FBcdfomJ:-NHf1vhlAp80ch1w0zRX:b-m0x2m) ([raw file](https://github.com/pyomeca/biorbd/blob/a4178563495f4313bd311ccbf6154af95cda231a/examples/cpp_eigen_installed/test.includes#L)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I don't think this file is supposed to be added
</blockquote></details>

Done. Sorry for all those test.xx  files ... 
___
*[`include/InternalForces/Muscles/Muscle.h` line 6 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5uclgETWjxRmpFomn:-NHf25W07kh4NjT5Z0vD:b-vhtwmc) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/include/InternalForces/Muscles/Muscle.h#L6)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

You did not remove the include but moved it. If should be forward declaration
</blockquote></details>

Need to be forward, if not I have and error.
___
*[`src/ModelReader.cpp` line 1107 at r4](https://reviewable.io/reviews/pyomeca/biorbd/312#-NHey8zE9MERV906lDEg:-NHf2GQMAErAoV2xWcwB:b-4t2pbo) ([raw file](https://github.com/pyomeca/biorbd/blob/a4178563495f4313bd311ccbf6154af95cda231a/src/ModelReader.cpp#L1107)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Did you mean `!std::isnan(slope)`?
</blockquote></details>

I think so ... 
___
*[`src/InternalForces/PassiveTorques/PassiveTorques.cpp` line 61 at r4](https://reviewable.io/reviews/pyomeca/biorbd/312#-NHezJ812zqYsgv6VSt8:-NHf3YAM2LX9tpaJvnpk:b-iva95g) ([raw file](https://github.com/pyomeca/biorbd/blob/a4178563495f4313bd311ccbf6154af95cda231a/src/InternalForces/PassiveTorques/PassiveTorques.cpp#L61)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Typically, you would use `other`. What means `Tp`?
</blockquote></details>

Stand for temporary. But I used other instead.


<!-- Sent from Reviewable.io -->

2022-11-24 19:26 UTC, aceglia reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/312)* status: 64 of 73 files reviewed, 9 unresolved discussions (waiting on @pariterre)

___
*[`include/InternalForces/Muscles/Muscle.h` line 6 at r2](https://reviewable.io/reviews/pyomeca/biorbd/312#-NH5uclgETWjxRmpFomn:-NHf5nAo558FpBorTZxw:b-jm8hjo) ([raw file](https://github.com/pyomeca/biorbd/blob/86b9158d4576e09d6450e1a2a2113dd79bafc585/include/InternalForces/Muscles/Muscle.h#L6)):*
<details><summary><i>Previously, aceglia wrote…</i></summary><blockquote>

Need to be forward, if not I have and error.
</blockquote></details>

Need to be actual import. 


<!-- Sent from Reviewable.io -->

2022-11-30 12:18 UTC, aceglia commented
@pariterre RTR

2022-12-01 19:19 UTC, pariterre requested changes
> Reviewed 30 of 39 files at r6, 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/312)* status: all files reviewed, 17 unresolved discussions (waiting on @aceglia)

___
*[`src/ModelReader.cpp` line 1081 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE-0pP2ngzG2UfELUh:-NIE-0pP2ngzG2UfELUi:b-syu5ve) ([raw file](https://github.com/pyomeca/biorbd/blob/e2e3ac4abd1c08568fada868c9433fdda822c92b/src/ModelReader.cpp#L1081)):*
> ```cpp
>                 }
>                 // Verify that everything is there
>                 utils::Error::check(isTypeSet!=0, "PassiveTorque type must be defined");
> ```

Ligaments?



_Code quote:_
```cpp
PassiveTorque
```
___
*[`src/ModelReader.cpp` line 1099 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE-9a48wh5xxL2i6L3:-NIE-9a48wh5xxL2i6L4:b-viy2xz) ([raw file](https://github.com/pyomeca/biorbd/blob/e2e3ac4abd1c08568fada868c9433fdda822c92b/src/ModelReader.cpp#L1099)):*
> ```cpp
>                 }
>                 model->addLigament(*ligament);
> #else // MODULE_MUSCLES
> ```

LIGAMENTS



_Code quote:_
```cpp
// MODULE_MUSCLES
```
___
*[`src/ModelReader.cpp` line 1100 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE-BrU9YQ7S1balC7C:-NIE-BrU9YQ7S1balC7D:bqk7kbd) ([raw file](https://github.com/pyomeca/biorbd/blob/e2e3ac4abd1c08568fada868c9433fdda822c92b/src/ModelReader.cpp#L1100)):*
> ```cpp
>                 model->addLigament(*ligament);
> #else // MODULE_MUSCLES
>                 utils::Error::raise("Biorbd was build without the module Muscles but the model defines a muscle");
> ```

Ligaments



_Code quote:_
```cpp
Muscles
```
___
*[`src/ModelReader.cpp` line 1101 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE-Dw07WnFQlGwnI5B:-NIE-Dw07WnFQlGwnI5C:bqk7kbd) ([raw file](https://github.com/pyomeca/biorbd/blob/e2e3ac4abd1c08568fada868c9433fdda822c92b/src/ModelReader.cpp#L1101)):*
> ```cpp
> #else // MODULE_MUSCLES
>                 utils::Error::raise("Biorbd was build without the module Muscles but the model defines a muscle");
> #endif // MODULE_MUSCLES
> ```

Ligaments



_Code quote:_
```cpp
MODULE_MUSCLES
```
___
*[`src/ModelReader.cpp` line 1223 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE-n2bBZw_YrJO_jbO:-NIE-n2bBZw_YrJO_jbP:bi899t4) ([raw file](https://github.com/pyomeca/biorbd/blob/e2e3ac4abd1c08568fada868c9433fdda822c92b/src/ModelReader.cpp#L1223)):*
> ```cpp
>                         utils::Error::check(model->IsBodyId(idx),
>                                                     "Wrong origin parent name for a muscle");
> #ifdef MODULE_MUSCLES
> ```

Probably useless



_Code quote:_
```cpp
#ifdef MODULE_MUSCLES
```
___
*[`src/ModelReader.cpp` line 1226 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE07_L4xDIHDZv55OX:-NIE07_L4xDIHDZv55OY:b-doyuxa) ([raw file](https://github.com/pyomeca/biorbd/blob/e2e3ac4abd1c08568fada868c9433fdda822c92b/src/ModelReader.cpp#L1226)):*
> ```cpp
>                     } else if (!property_tag.tolower().compare("muscle")) {
>                         file.read(muscle);
>                         isMuscle = true;
> ```

check(!isLigament) 



_Code quote:_
```cpp
isMuscle = true;
```
___
*[`src/ModelReader.cpp` line 1232 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE-pBY3908EcDYew-F:-NIE-pBY3908EcDYew-G:bi899t4) ([raw file](https://github.com/pyomeca/biorbd/blob/e2e3ac4abd1c08568fada868c9433fdda822c92b/src/ModelReader.cpp#L1232)):*
> ```cpp
>                 utils::Error::raise("Biorbd was build without the muscle module but the model defines a viapoint.")
> #endif
> #ifdef MODULE_LIGAMENTS
> ```

Probably useless



_Code quote:_
```cpp
#ifdef MODULE_LIGAMENTS
```
___
*[`src/ModelReader.cpp` line 1235 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0EKuA2pJjdYVFPwZ:-NIE0EKuA2pJjdYVFPw_:b-h3ybv2) ([raw file](https://github.com/pyomeca/biorbd/blob/e2e3ac4abd1c08568fada868c9433fdda822c92b/src/ModelReader.cpp#L1235)):*
> ```cpp
>                     } else if (!property_tag.tolower().compare("ligament")) {
>                         file.read(ligament);
>                         isLigament=true;
> ```

check(!isMuscle)



_Code quote:_
```cpp
isLigament=true;
```
___
*[`src/ModelReader.cpp` line 1297 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0LAx5I_zN7neDDK9:-NIE0LAx5I_zN7neDDKA:b413eij) ([raw file](https://github.com/pyomeca/biorbd/blob/e2e3ac4abd1c08568fada868c9433fdda822c92b/src/ModelReader.cpp#L1297)):*
> ```cpp
>                     } else if (!property_tag.tolower().compare("type")) {
>                         file.read(wrapType);
> #ifdef MODULE_MUSCLES
> ```

Probably not useful



_Code quote:_
```cpp
#ifdef MODULE_MUSCLES
```
___
*[`src/ModelReader.cpp` line 1300 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0OC15i9F13qZ0Cr-:-NIE0OC15i9F13qZ0Cr0:b-mlgjvi) ([raw file](https://github.com/pyomeca/biorbd/blob/e2e3ac4abd1c08568fada868c9433fdda822c92b/src/ModelReader.cpp#L1300)):*
> ```cpp
>                     } else if (!property_tag.tolower().compare("muscle")) {
>                         file.read(muscle);
>                         isMuscle=true;
> ```

add check ligaments



_Code quote:_
```cpp
isMuscle=true;
```
___
*[`src/ModelReader.cpp` line 1306 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0PhEE-m3KlbR8ECQ:-NIE0PhEE-m3KlbR8ECR:b413eij) ([raw file](https://github.com/pyomeca/biorbd/blob/e2e3ac4abd1c08568fada868c9433fdda822c92b/src/ModelReader.cpp#L1306)):*
> ```cpp
>                 utils::Error::raise("Biorbd was build without the muscle module but the model defines a wrapping object.")
> #endif
> #ifdef MODULE_LIGAMENTS
> ```

Probably not useful



_Code quote:_
```cpp
#ifdef MODULE_LIGAMENTS
```
___
*[`src/ModelReader.cpp` line 1309 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0Q_pADyakwHtCC0h:-NIE0Q_pADyakwHtCC0i:b-ivcp6x) ([raw file](https://github.com/pyomeca/biorbd/blob/e2e3ac4abd1c08568fada868c9433fdda822c92b/src/ModelReader.cpp#L1309)):*
> ```cpp
>                     } else if (!property_tag.tolower().compare("ligament")) {
>                         file.read(ligament);
>                         isLigament=true;
> ```

add check isMuscle



_Code quote:_
```cpp
isLigament=true;
```
___
*[`src/ModelReader.cpp` line 1328 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0WIW2N9PgfAVeq-a:-NIE0WIW2N9PgfAVeq-b:b1lu2rt) ([raw file](https://github.com/pyomeca/biorbd/blob/e2e3ac4abd1c08568fada868c9433fdda822c92b/src/ModelReader.cpp#L1328)):*
> ```cpp
>                 }
>                 internal_forces::WrappingHalfCylinder cylinder(RT,radius,length,name,parent);
>                 if (isMuscle && isLigament!=1) {
> ```

Not useful anymore



_Code quote:_
```cpp
&& isLigament!=1
```
___
*[`src/ModelReader.cpp` line 1335 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0Z3lCQBz1pZb2oes:-NIE0Z3lCQBz1pZb2oet:b1lu2rt) ([raw file](https://github.com/pyomeca/biorbd/blob/e2e3ac4abd1c08568fada868c9433fdda822c92b/src/ModelReader.cpp#L1335)):*
> ```cpp
>                     utils::Error::check(iMuscle!=-1, "No muscle was provided!");                    model->muscleGroup(static_cast<unsigned int>(iMuscleGroup)).muscle(
>                         static_cast<unsigned int>(iMuscle)).addPathObject(cylinder);
>                  } else if (isLigament && isMuscle!=1) {
> ```

Not useful anymore



_Code quote:_
```cpp
&& isMuscle!=1
```
___
*[`src/ModelReader.cpp` line 1337 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0dLtCuqSS3dxhcik:-NIE0dLtCuqSS3dxhcil:b-9njgb1) ([raw file](https://github.com/pyomeca/biorbd/blob/e2e3ac4abd1c08568fada868c9433fdda822c92b/src/ModelReader.cpp#L1337)):*
> ```cpp
>                  } else if (isLigament && isMuscle!=1) {
>                     iLigament = model->ligamentID(ligament);
>                     utils::Error::check(iLigament!=-1, "No muscle was provided!");
> ```

Don't understand this check
___
*[` [...]

2022-12-14 14:18 UTC, pariterre requested changes
> Reviewed 12 of 13 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/312)* status: 91 of 92 files reviewed, 3 unresolved discussions (waiting on @aceglia)

___
*[`src/ModelReader.cpp` line 1265 at r8](https://reviewable.io/reviews/pyomeca/biorbd/312#-NJFyyEv-6UZsBuOJoz1:-NJFyyEv-6UZsBuOJoz2:bf44t6k) ([raw file](https://github.com/pyomeca/biorbd/blob/36a487a080eaee43de90be923ef34b79dcb346ac/src/ModelReader.cpp#L1265)):*
> ```cpp
>                 bool isMuscle=false;
>                 bool isLigament=false;
>                 int iLigament(-1);
> ```

what do `i` stands for? if it is `index`please at least write `idx`



_Code quote:_
```cpp
int iLigament(-1);
```
___
*[`test/test_muscles.cpp` line 316 at r8](https://reviewable.io/reviews/pyomeca/biorbd/312#-NJFznEk0eRLhPjwjh2P:-NJFznEl4lO5KCqwV3st:bqcvneq) ([raw file](https://github.com/pyomeca/biorbd/blob/36a487a080eaee43de90be923ef34b79dcb346ac/test/test_muscles.cpp#L316)):*
> ```cpp
>                 SCALAR_TO_DOUBLE(deepCopyNowLength, deepCopyNow.position().length());
>                 SCALAR_TO_DOUBLE(deepCopyLaterLength, deepCopyLater.position().length());
>                 EXPECT_NEAR(length, 0.45796092269003846, requiredPrecision);
> ```

why did the length change?
___
*[`test/test_passive_torques.cpp` line 67 at r8](https://reviewable.io/reviews/pyomeca/biorbd/312#-NJFzuF96LEFDgymVU8S:-NJFzuFA8Qvg-8SYClX0:bltlh7v) ([raw file](https://github.com/pyomeca/biorbd/blob/36a487a080eaee43de90be923ef34b79dcb346ac/test/test_passive_torques.cpp#L67)):*
> ```cpp
>     FILL_VECTOR(Q, val);
>     FILL_VECTOR(Qdot, val);
>     double torqueExponentialExpected(27.237093441022679);
> ```

Is that expected?


<!-- Sent from Reviewable.io -->

2022-12-14 14:28 UTC, aceglia reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/312)* status: 91 of 92 files reviewed, 3 unresolved discussions (waiting on @pariterre)

___
*[`src/ModelReader.cpp` line 1081 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE-0pP2ngzG2UfELUh:-NIEjD2a6j-N4exrY2_q:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/ModelReader.cpp#L1081)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Ligaments?
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1099 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE-9a48wh5xxL2i6L3:-NIEjDwV34ewEUyU1gzM:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/ModelReader.cpp#L1099)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

LIGAMENTS
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1100 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE-BrU9YQ7S1balC7C:-NIEjEfQEJ_0euluVEeG:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/ModelReader.cpp#L1100)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Ligaments
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1101 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE-Dw07WnFQlGwnI5B:-NIEjFDd44UGy40uZ1RU:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/ModelReader.cpp#L1101)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Ligaments
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1223 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE-n2bBZw_YrJO_jbO:-NIEjzFo0EyO4Lgsn4Qq:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/ModelReader.cpp#L1223)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Probably useless
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1226 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE07_L4xDIHDZv55OX:-NIEjziw3aCe-MXW76ne:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/ModelReader.cpp#L1226)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

check(!isLigament) 
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1232 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE-pBY3908EcDYew-F:-NIEk3vC65H5ZmVxWUq3:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/ModelReader.cpp#L1232)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Probably useless
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1235 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0EKuA2pJjdYVFPwZ:-NIEk4C878-tlSUgPTo5:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/ModelReader.cpp#L1235)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

check(!isMuscle)
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1297 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0LAx5I_zN7neDDK9:-NIEk5r7ARQHeSwoV77G:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/ModelReader.cpp#L1297)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Probably not useful
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1300 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0OC15i9F13qZ0Cr-:-NIEk69s0MYVx8dvdVes:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/ModelReader.cpp#L1300)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

add check ligaments
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1306 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0PhEE-m3KlbR8ECQ:-NIEk6YkDV0sMJzUlvTC:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/ModelReader.cpp#L1306)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Probably not useful
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1309 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0Q_pADyakwHtCC0h:-NIEk6ys5-Rhz84BR6D3:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/ModelReader.cpp#L1309)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

add check isMuscle
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1328 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0WIW2N9PgfAVeq-a:-NIEk7Y37uOyUGT8EH9A:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/ModelReader.cpp#L1328)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Not useful anymore
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1335 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0Z3lCQBz1pZb2oes:-NIEk807-jgH0xPi5R6n:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/ModelReader.cpp#L1335)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Not useful anymore
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1337 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0dLtCuqSS3dxhcik:-NIEkHnO86m9CdmI8qe0:bss4a2b) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/ModelReader.cpp#L1337)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Don't understand this check
</blockquote></details>

Removed.
___
*[`src/ModelReader.cpp` line 1340 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE0n-M4DTIZPwaixrG:-NIEkJuR9mOMp-5cyZWX:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/ModelReader.cpp#L1340)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Move that to the previous checks
</blockquote></details>

Done.
___
*[`src/ModelReader.cpp` line 1265 at r8](https://reviewable.io/reviews/pyomeca/biorbd/312#-NJFyyEv-6UZsBuOJoz1:-NJG0Zsr3X1YJHExNgcq:b-96e4md) ([raw file](https://github.com/pyomeca/biorbd/blob/36a487a080eaee43de90be923ef34b79dcb346ac/src/ModelReader.cpp#L1265)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

what do `i` stands for? if it is `index`please at least write `idx`
</blockquote></details>

Done in the next commit.
___
*[`src/InternalForces/Ligaments/LigamentConstant.cpp` line 106 at r7](https://reviewable.io/reviews/pyomeca/biorbd/312#-NIE3VqfEBCwZJLWcWof:-NIEkKvk-wt-1tnaA1gb:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/42a188a0381ed93bfee4d2461548acdd997168a8/src/InternalForces/Ligaments/LigamentConstant.cpp#L106)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Do not test for ligament Slack length. Constant means constant
</blockquote></details>

Done.
___
*[`test/test_muscles.cpp` line 316 at r8](https://reviewable.io/reviews/pyomeca/biorbd/312#-NJFznEk0eRLhPjwjh2P:-NJG0bSo4hkLYPj6AKx7:b-ojlwz1) ([raw file](https://github.com/pyomeca/biorbd/blob/36a487a080eaee43de90be923ef34b79dcb346ac/test/test_muscles.cpp#L316)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

why did [...]

2022-12-14 14:49 UTC, pariterre approved these changes
> Reviewed 1 of 13 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/312)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aceglia)



<!-- Sent from Reviewable.io -->

2022-12-15 18:44 UTC, pariterre approved these changes
> Reviewed 15 of 15 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/312)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aceglia)



<!-- Sent from Reviewable.io -->

2023-01-17 20:14 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/312#-:-NM0MUmv3asiVGTW7V2S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aceglia)



<!-- Sent from Reviewable.io -->

2023-01-17 20:28 UTC, merged